spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sprout?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: www.jiexian.biz
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      database: 1
      host: localhost
      port: 6379

  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

mybatis:
  type-aliases-package: me.kujio.sprout.**.entity
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath*:mapper/base/*Mapper.xml

logging:
  level:
    me.kujio.sprout: debug
#    org.springframework.security: debug

server:
  tomcat:
    accept-count: 100
    max-connections: 10000
    connection-timeout: 60s
  port: 8081

token:
  header: Authorization
  validity: 10
  secret: jmazbshytwqlnogxirvdpucefkdczu

files:
  root: D:\SRC\Web\sprout-service\files\
  upload: upload\
  download: download\
  resource: resource\